select * from emp;--where ename IN ('SMITH', 'ALLEN','FORD');

select * from dept;

select * from emp where DEPTNO = (SELECT DEPTNO from dept where DNAME = 'SALES');

--SELECT JOB,AVG(SAL) FROM EMP WHERE SAL > 2500 GROUP BY JOB;

SELECT D.DEPTNO, AVG(E.SAL), MAX(E.SAL), MIN(E.SAL), SUM(E.SAL) FROM EMP E
JOIN DEPT D ON D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO
ORDER BY D.DEPTNO;

SELECT COUNT(EMPNO) FROM EMP WHERE SAL >= 3000;

SELECT D.DNAME, COUNT(E.EMPNO) FROM EMP E
RIGHT JOIN DEPT D ON D.DEPTNO = E.DEPTNO
WHERE E.SAL >= 3000
GROUP BY D.DNAME;

SELECT D.DNAME, AVG(E.SAL) FROM EMP E
RIGHT JOIN DEPT D ON D.DEPTNO = E.DEPTNO
GROUP BY D.DNAME 
ORDER BY D.DNAME ASC;

SELECT COUNT(E.EMPNO) FROM EMP E;

SELECT D.DNAME, COUNT(E.ENAME) FROM EMP E
RIGHT JOIN DEPT D ON D.DEPTNO = E.DEPTNO
WHERE 2 < (
  SELECT COUNT(E.EMPNO) FROM EMP E
  RIGHT JOIN DEPT D ON D.DEPTNO = E.DEPTNO
  GROUP BY D.DNAME
  )
GROUP BY D.DNAME 
ORDER BY D.DNAME;



SELECT E.ENAME, E.SAL FROM EMP E
WHERE E.SAL > (SELECT AVG(E.SAL) FROM EMP E);

SELECT D.DEPTNO, E.SAL, COUNT(E.EMPNO) 
FROM DEPT D JOIN EMP E
ON D.DEPTNO = E.DEPTNO
JOIN EMP E2
ON E.EMPNO = E2.EMPNO
WHERE E.SAL = E2.SAL
HAVING COUNT(E.EMPNO) > 1
GROUP BY D.DEPTNO,E.SAL
ORDER BY DEPTNO;

SELECT D.DNAME, D.LOC, COUNT(E.EMPNO) 
FROM DEPT D JOIN EMP E
ON D.DEPTNO = E.DEPTNO
HAVING COUNT(E.EMPNO) > 1
GROUP BY D.DNAME,D.LOC;

SELECT D.DNAME, COUNT(E.EMPNO) 
FROM DEPT D 
JOIN EMP E
ON D.DEPTNO = E.DEPTNO
--HAVING COUNT(E1.EMPNO) > 1
GROUP BY D.DEPTNO;