/*
 * File: app/controller/HomePage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BurgerQueen.controller.HomePage', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'beveragesButton',
            selector: '#beveragesButton'
        },
        {
            ref: 'burgersButton',
            selector: '#burgersButton'
        },
        {
            ref: 'chickensButton',
            selector: '#chickensButton'
        },
        {
            ref: 'dessertsButton',
            selector: '#dessertsButton'
        },
        {
            ref: 'sidesButton',
            selector: '#sidesButton'
        },
        {
            ref: 'loginButton',
            selector: '#loginButton'
        },
        {
            ref: 'logoutButton',
            selector: '#logoutButton'
        },
        {
            ref: 'productGrid',
            selector: '#ProductGrid'
        },
        {
            ref: 'productViewWindow',
            selector: '#ProductView'
        }
    ],

    onLoginButtonClick: function() {
                Ext.create('BurgerQueen.view.LoginWindow').show();
    },

    onBeveragesButtonClick: function() {

                var productStore = this.productStore;

                productStore.clearFilter();
                productStore.filter('Category','Beverages');

    },

    onBurgersButtonClick: function() {
                     var productStore = this.productStore;

                        productStore.clearFilter();
                        productStore.filter('Category','Burgers');
    },

    onChickensButtonClick: function() {
                 var productStore = this.productStore;

                        productStore.clearFilter();
                        productStore.filter('Category','Chickens');
    },

    onDessertsButtonClick: function() {
             var productStore = this.productStore;

                        productStore.clearFilter();
                        productStore.filter('Category','Desserts');
    },

    onSidesButtonClick: function() {
         var productStore = this.productStore;

                        productStore.clearFilter();
                        productStore.filter('Category','Sides');
    },

    onLogoutButtonClick: function() {

    },

    onProductGridItemDblClick: function() {
                 var productStore = this.productStore;

                var productGrid = this.getProductGrid(),
                    selectModel = productGrid.getSelectionModel(),
                    selectedProduct = selectModel.getSelection()[0].data;

        //         var selectedProductName = selectedProduct.name,
        //         	selectedProductPrice = selectedProduct.price,
        //         	selectedProductDesc = selectedProduct.description;

        //         this.getProductName().setValue(selectedProductName);
        //         this.getProductPrice().setValue(selectedProductPrice);
        //         this.getProductDesc().setValue(selectedProductDesc);

                var productWin = Ext.create('BurgerQueen.view.ProductViewWindow',{selectedProduct: selectedProduct});
                productWin.show();
                Ext.getBody().mask();
    },

    onTrayBtnClick: function() {
         Ext.create('BurgerQueen.view.TrayWindow').show();
    },

    onLaunch: function() {
                this.productStore = Ext.getStore('ProductStore');

    },

    init: function(application) {
        this.control({
            "#loginButton": {
                click: this.onLoginButtonClick
            },
            "#beveragesButton": {
                click: this.onBeveragesButtonClick
            },
            "#burgersButton": {
                click: this.onBurgersButtonClick
            },
            "#chickensButton": {
                click: this.onChickensButtonClick
            },
            "#dessertsButton": {
                click: this.onDessertsButtonClick
            },
            "#sidesButton": {
                click: this.onSidesButtonClick
            },
            "#logoutButton": {
                click: this.onLogoutButtonClick
            },
            "#ProductGrid": {
                itemdblclick: this.onProductGridItemDblClick
            },
            "#trayBtn": {
                click: this.onTrayBtnClick
            }
        });
    }

});
