/*
 * File: resources/app/view/RegisterWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BurgerQueen.view.RegisterWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 600,
    html: '<center><div id="nav"><h2 style = \'font-family: Abel;\'>Register</h2></div></center>',
    itemId: 'registerWindow',
    style: 'font-family: \'Abel\';',
    width: 462,
    layout: 'fit',
    header: false,
    title: 'My Window',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'registerForm',
                    bodyPadding: 10,
                    bodyStyle: 'font-family: \'Century Gothic\';',
                    header: false,
                    title: 'Register',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            flex: 1,
                            height: 60,
                            html: '<center><div><h1 style = \'font-family: Arial; color:#565652; \'>Register</h1></div></center>',
                            margin: '0, 0, 35, 0',
                            width: 400,
                            fieldLabel: ''
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            rtl: false,
                            width: 160,
                            fieldLabel: 'User Name',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'username',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            id: 'password',
                            itemId: '',
                            width: 420,
                            fieldLabel: 'Password',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'password',
                            inputType: 'password',
                            allowBlank: false,
                            minLength: 6
                        },
                        {
                            xtype: 'textfield',
                            validator: function(value) {
                                if(Ext.getCmp('password').getValue() !== value){
                                    Ext.getCmp('confirmpassword').markInvalid('Password does not match');
                                    return "Password does not match";
                                }else{
                                    return true;
                                }
                            },
                            flex: 1,
                            id: 'confirmpassword',
                            itemId: 'confirmpassword',
                            width: 420,
                            fieldLabel: 'Confirm Password',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'confirmpassword',
                            inputType: 'password',
                            allowBlank: false,
                            minLength: 6
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'First Name',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'firstname',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Middle Name',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'middlename'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Last Name',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'lastname',
                            allowBlank: false
                        },
                        {
                            xtype: 'textareafield',
                            flex: 1,
                            fieldLabel: 'Address',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'address',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Contact No.',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'contactno',
                            inputType: 'tel',
                            allowBlank: false,
                            maskRe: /^[0-9]*$/,
                            maxLength: 12
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Email',
                            labelSeparator: '<span style="color: rgb(255, 0, 0); padding-left: 2px;">*</span>:',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            labelWidth: 160,
                            name: 'email',
                            invalidText: 'Email is invalid',
                            allowBlank: false,
                            emptyText: 'sample@email.com',
                            regex: /^[a-zA-Z0-9_%+-]+@[a-zA-Z0-9-]+\.[a-zA-Z]{2,}/
                        },
                        {
                            xtype: 'radiogroup',
                            flex: 1,
                            width: 400,
                            fieldLabel: 'Gender',
                            labelAlign: 'right',
                            labelStyle: 'font-family: \'Abel\'; font-size: 20px;',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    name: 'gender',
                                    boxLabel: 'Male',
                                    checked: true,
                                    inputValue: 'Male'
                                },
                                {
                                    xtype: 'radiofield',
                                    name: 'gender',
                                    boxLabel: 'Female',
                                    inputValue: 'Female'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'registerWindowButton',
                            text: 'Register'
                        },
                        {
                            xtype: 'button',
                            id: 'cancelRegisterButton',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});