--------------------------------------------------------
--  File created - Friday-July-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEAL
--------------------------------------------------------

  CREATE TABLE "GROUP1"."MEAL" 
   (	"ID" NUMBER(15,0), 
	"CODE" VARCHAR2(40 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICE" FLOAT(126), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"IMAGE" VARCHAR2(200 BYTE), 
	"CATEGORY" VARCHAR2(50 BYTE), 
	"POINTS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT" ;
--------------------------------------------------------
--  DDL for Index SYS_C007353
--------------------------------------------------------

  CREATE UNIQUE INDEX "GROUP1"."SYS_C007353" ON "GROUP1"."MEAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT" ;
--------------------------------------------------------
--  DDL for Index SYS_C007354
--------------------------------------------------------

  CREATE UNIQUE INDEX "GROUP1"."SYS_C007354" ON "GROUP1"."MEAL" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT" ;
--------------------------------------------------------
--  Constraints for Table MEAL
--------------------------------------------------------

  ALTER TABLE "GROUP1"."MEAL" MODIFY ("POINTS" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."MEAL" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."MEAL" ADD CONSTRAINT "MEAL_CODE" UNIQUE ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT"  ENABLE;
  ALTER TABLE "GROUP1"."MEAL" ADD CONSTRAINT "PK_MEAL_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT"  ENABLE;
  ALTER TABLE "GROUP1"."MEAL" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."MEAL" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."MEAL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."MEAL" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."MEAL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger MEAL_ID_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GROUP1"."MEAL_ID_TRIG" 
BEFORE INSERT ON MEAL
FOR EACH ROW
BEGIN
IF :NEW.ID IS NULL THEN
SELECT MEAL_ID_SEQ.nextval INTO :NEW.ID FROM SYS.DUAL;
END IF;
END;
/
ALTER TRIGGER "GROUP1"."MEAL_ID_TRIG" ENABLE;
