--------------------------------------------------------
--  File created - Friday-July-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRAY
--------------------------------------------------------

  CREATE TABLE "GROUP1"."TRAY" 
   (	"ID" NUMBER(15,0), 
	"USER_ID" NUMBER(15,0), 
	"MEAL_ID" NUMBER(15,0), 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT" ;
--------------------------------------------------------
--  DDL for Index TRAY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GROUP1"."TRAY_PK" ON "GROUP1"."TRAY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT" ;
--------------------------------------------------------
--  Constraints for Table TRAY
--------------------------------------------------------

  ALTER TABLE "GROUP1"."TRAY" ADD CONSTRAINT "TRAY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT"  ENABLE;
  ALTER TABLE "GROUP1"."TRAY" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."TRAY" MODIFY ("MEAL_ID" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."TRAY" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."TRAY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TRAY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GROUP1"."TRAY_TRG" 
BEFORE INSERT ON TRAY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TRAY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "GROUP1"."TRAY_TRG" ENABLE;
