/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Homework.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.View',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.field.Date',
        'Ext.grid.plugin.RowEditing',
        'Ext.form.Panel',
        'Ext.form.field.TextArea'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Homework 1',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 400,
                                    itemId: 'employeeGrid',
                                    title: 'Employee Information',
                                    store: 'EmpStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'id',
                                            text: 'Id',
                                            flex: 1,
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'firstname',
                                            text: 'Firstname',
                                            flex: 1,
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'middlename',
                                            text: 'Middlename',
                                            flex: 1,
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'lastname',
                                            text: 'Lastname',
                                            flex: 1,
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'Birthdate',
                                            text: 'Birthdate',
                                            flex: 1,
                                            editor: {
                                                xtype: 'datefield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'City',
                                            text: 'City',
                                            flex: 1,
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'State',
                                            text: 'State',
                                            flex: 1,
                                            editor: {
                                                xtype: 'textfield'
                                            }
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle'
                                            },
                                            items: [
                                                {
                                                    xtype: 'tbfill'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Create',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Load Data',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick1,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Save',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick2,
                                                            scope: me
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete',
                                                    listeners: {
                                                        click: {
                                                            fn: me.onButtonClick3,
                                                            scope: me
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ],
                                    plugins: [
                                        Ext.create('Ext.grid.plugin.RowEditing', {

                                        })
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Homework 2',
                            items: [
                                {
                                    xtype: 'form',
                                    bodyPadding: 10,
                                    title: 'Employee Information',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'ID'
                                        },
                                        {
                                            xtype: 'container'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Firstname'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Middlename'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Lastname'
                                        },
                                        {
                                            xtype: 'datefield',
                                            anchor: '100%',
                                            fieldLabel: 'Birthdate'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            fieldLabel: 'Address'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'City'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'State'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'bottom',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    text: 'Create'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Read Data'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Update'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Delete'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Reset'
                                                },
                                                {
                                                    xtype: 'tbfill'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Homework 3',
                            items: [
                                {
                                    xtype: 'panel',
                                    html: '<table border=2><tr><td>THIS IS GENERATED</td></tr><tr><td>Generated</td></tr></table>',
                                    title: 'Dynamic Table',
                                    items: [
                                        {
                                            xtype: 'button',
                                            text: 'MyButton',
                                            listeners: {
                                                click: {
                                                    fn: me.onButtonClick4,
                                                    scope: me
                                                }
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
            var emp = {
                firstname: '',
                lastname: '',
                middlename: ''
            };
            Ext.getStore('EmpStore').add(emp);
    },

    onButtonClick1: function(button, e, eOpts) {
            var data = [
                        {
                            id: 465,
                            firstname: 'Lloyd',
                            middlename: 'Beatrice',
                            lastname: 'Turner',
                            Birthdate: '9/28/2001',
                            City: 'Exercitationem',
                            State: 'CT'
                        },
                        {
                            id: 188,
                            firstname: 'Blanche',
                            middlename: 'Lewis',
                            lastname: 'Morgan',
                            Birthdate: '7/12/2001',
                            City: 'Veritatis',
                            State: 'GU'
                        },
                        {
                            id: 237,
                            firstname: 'Ed',
                            middlename: 'Alma',
                            lastname: 'Carter',
                            Birthdate: '10/22/2013',
                            City: 'Necessitatibus',
                            State: 'PW'
                        },
                        {
                            id: 176,
                            firstname: 'Ben',
                            middlename: 'Maude',
                            lastname: 'Johnson',
                            Birthdate: '10/11/2001',
                            City: 'Corporis',
                            State: 'ID'
                        },
                        {
                            id: 947,
                            firstname: 'Mattie',
                            middlename: 'Marguerite',
                            lastname: 'Parker',
                            Birthdate: '7/27/2004',
                            City: 'Reprehenderit',
                            State: 'NE'
                        },
                        {
                            id: 237,
                            firstname: 'Lloyd',
                            middlename: 'Lloyd',
                            lastname: 'Mitchell',
                            Birthdate: '10/9/2005',
                            City: 'Labore',
                            State: 'NV'
                        },
                        {
                            id: 739,
                            firstname: 'Anthony',
                            middlename: 'Oliver',
                            lastname: 'Brooks',
                            Birthdate: '1/23/2003',
                            City: 'Rerum',
                            State: 'SC'
                        },
                        {
                            id: 366,
                            firstname: 'Edwin',
                            middlename: 'Ray',
                            lastname: 'Parker',
                            Birthdate: '11/2/2001',
                            City: 'Accusantium',
                            State: 'IN'
                        },
                        {
                            id: 708,
                            firstname: 'Ray',
                            middlename: 'Ada',
                            lastname: 'Scott',
                            Birthdate: '8/17/2014',
                            City: 'Ratione',
                            State: 'LA'
                        },
                        {
                            id: 104,
                            firstname: 'Sadie',
                            middlename: 'Otto',
                            lastname: 'Cook',
                            Birthdate: '1/19/2005',
                            City: 'Voluptatem',
                            State: 'UT'
                        }
                    ];

            Ext.getStore('EmpStore').loadData(data);
    },

    onButtonClick2: function(button, e, eOpts) {

            Ext.Msg.alert('Save Successfully', 'Record was saved successfully');
    },

    onButtonClick3: function(button, e, eOpts) {
            var grid = button.up('gridpanel'),
                sel = grid.getSelectionModel();
            Ext.getStore('EmpStore').remove(sel);
    },

    onButtonClick4: function(button, e, eOpts) {
                button.up('panel').html ='try';
    }

});