CREATE TABLE STUDENT (
STUDENT_ID VARCHAR2(100) PRIMARY KEY NOT NULL,
STUDENT_NAME VARCHAR(100) ,
STUDENT_SCORE NUMBER(38,0),
STUDENT_TEACHERID VARCHAR(100) NOT NULL,
CONSTRAINT FK_TECHERID FOREIGN KEY (STUDENT_TEACHERID)
REFERENCES TEACHER(TEACHER_ID)
);
CREATE TABLE TEACHER (
TEACHER_ID VARCHAR2(100) NOT NULL PRIMARY KEY,
TEACHER_NAME VARCHAR(100),
TEACHER_SCHOOL_NAME VARCHAR2(100));

insert into teacher values('1','Imelda Papins','Integrated School For Gifted Singers');

insert into student values('1','Charlie Puth', 95, '1');
insert into student values('2','Adam Levigne', 96, '1');