
--1
SELECT * FROM EMP WHERE SAL > 3000;

--2
SELECT * FROM EMP WHERE ENAME LIKE 'S%';

--3
SELECT * FROM EMP WHERE ENAME IN ('SMITH', 'ALLEN', 'FORD');

--4
SELECT E.* FROM EMP E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'SALES';

--5
SELECT D.DEPTNO, AVG(E.SAL) AS "AVERAGE SALARY",
MAX(E.SAL) AS "MAX SALARY",
MIN(E.SAL) AS "SMALLEST SALARY",
SUM(E.SAL) AS "TOTAL SALARY"
FROM DEPT D
JOIN EMP E
ON D.DEPTNO = E.DEPTNO
GROUP BY D.DEPTNO
ORDER BY D.DEPTNO;

--6
SELECT D.DNAME, COUNT(E.EMPNO) FROM DEPT D
JOIN EMP E
ON D.DEPTNO = E.DEPTNO
WHERE E.SAL > 3000
GROUP BY D.DNAME;

--7
SELECT D.DNAME, AVG(E.SAL) FROM DEPT D
JOIN EMP E
ON D.DEPTNO = E.DEPTNO
GROUP BY D.DNAME
ORDER BY D.DNAME;

--8
SELECT D.DEPTNO, E.SAL, COUNT(E.EMPNO) AS COUNTEMP
FROM DEPT D JOIN EMP E
ON D.DEPTNO = E.DEPTNO
JOIN EMP E2
ON E.EMPNO = E2.EMPNO
WHERE E.SAL = E2.SAL
GROUP BY D.DEPTNO,E.SAL
HAVING COUNT(E.EMPNO) > 1;

-- OTHER WAY FOR NUMBER 8

SELECT E1.DEPTNO, E1.SAL, COUNT(E1.EMPNO)
FROM EMP E1 JOIN EMP E2
ON E1.EMPNO = E2.EMPNO
WHERE E1.SAL = E2.SAL
AND E1.DEPTNO = E2.DEPTNO
GROUP BY E1.DEPTNO, E1.SAL
HAVING COUNT(E1.EMPNO) > 1;

--9
SELECT D.DNAME, D.LOC, COUNT(E.EMPNO) FROM DEPT D
JOIN EMP E ON 
D.DEPTNO = E.DEPTNO
GROUP BY D.DNAME, D.LOC
HAVING COUNT(E.EMPNO) > 2;

--10
SELECT ENAME, SAL FROM EMP 
WHERE SAL > (SELECT AVG(SAL) FROM EMP);
