--------------------------------------------------------
--  File created - Friday-July-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERITEMS
--------------------------------------------------------

  CREATE TABLE "GROUP1"."ORDERITEMS" 
   (	"ID" NUMBER(15,0), 
	"ORDER_ID" NUMBER(15,0), 
	"MEAL_ID" NUMBER(15,0), 
	"QUANTITY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT" ;
--------------------------------------------------------
--  DDL for Index SYS_C007372
--------------------------------------------------------

  CREATE UNIQUE INDEX "GROUP1"."SYS_C007372" ON "GROUP1"."ORDERITEMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT" ;
--------------------------------------------------------
--  Constraints for Table ORDERITEMS
--------------------------------------------------------

  ALTER TABLE "GROUP1"."ORDERITEMS" ADD CONSTRAINT "PK_ORDERITEM_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WEEK5_PROJECT"  ENABLE;
  ALTER TABLE "GROUP1"."ORDERITEMS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."ORDERITEMS" MODIFY ("MEAL_ID" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."ORDERITEMS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "GROUP1"."ORDERITEMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDERITEMS
--------------------------------------------------------

  ALTER TABLE "GROUP1"."ORDERITEMS" ADD CONSTRAINT "FK_MEAL_ID" FOREIGN KEY ("MEAL_ID")
	  REFERENCES "GROUP1"."MEAL" ("ID") ENABLE;
  ALTER TABLE "GROUP1"."ORDERITEMS" ADD CONSTRAINT "FK_ORDER_ID" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "GROUP1"."ORDERS" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDERITEM_ID_TRIG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GROUP1"."ORDERITEM_ID_TRIG" 
BEFORE INSERT ON ORDERITEMS
FOR EACH ROW
BEGIN
IF :NEW.ID IS NULL THEN
SELECT ORDERITEMS_ID_SEQ.nextval INTO :NEW.ID FROM DUAL;
END IF;
END;
/
ALTER TRIGGER "GROUP1"."ORDERITEM_ID_TRIG" ENABLE;
