/*
 * File: app/view/UserProfile.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BurgerQueen.view.UserProfile', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.userprofile',

    requires: [
        'Ext.container.Container',
        'Ext.form.field.Display'
    ],

    height: 250,
    id: 'UserProfile',
    itemId: 'UserProfile',
    width: 400,
    layout: 'border',
    header: false,
    title: 'My Profile',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    region: 'center',
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'usernameProfile',
                            width: 150,
                            fieldLabel: 'Username',
                            value: 'Display Field',
                            inputId: 'userName'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'firstnameProfile',
                            width: 150,
                            fieldLabel: 'First name',
                            value: 'Display Field',
                            inputId: 'firstName'
                        },
                        {
                            xtype: 'displayfield',
                            height: 150,
                            itemId: 'middlenameProfile',
                            fieldLabel: 'Middle name:',
                            value: 'Display Field',
                            inputId: 'middleName'
                        },
                        {
                            xtype: 'displayfield',
                            height: 150,
                            id: 'lastnameProfile',
                            itemId: 'lastnameProfile',
                            fieldLabel: 'Last name',
                            value: 'Display Field',
                            inputId: 'lastName'
                        },
                        {
                            xtype: 'displayfield',
                            height: 150,
                            id: 'addressProfile',
                            itemId: 'addressProfile',
                            fieldLabel: 'Address',
                            value: 'Display Field',
                            inputId: 'address'
                        },
                        {
                            xtype: 'displayfield',
                            height: 150,
                            id: 'emailProfile',
                            itemId: 'emailProfile',
                            fieldLabel: 'E-mail',
                            value: 'Display Field',
                            inputId: 'email'
                        },
                        {
                            xtype: 'displayfield',
                            height: 150,
                            id: 'contactnumProfile',
                            itemId: 'contactnumProfile',
                            fieldLabel: 'Contact:',
                            value: 'Display Field',
                            inputId: 'userProfileWindow'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});