/*
 * File: app/view/registerWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Libray.view.registerWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Libray.view.RegisterForm',
        'Ext.form.Panel'
    ],

    height: 285,
    itemId: 'registerWindow',
    width: 380,
    layout: 'fit',
    bodyBorder: false,
    header: false,
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'registerForm',
                    layout: 'anchor'
                }
            ]
        });

        me.callParent(arguments);
    }

});