{
    "xdsVersion": "3.1.0",
    "frameworkVersion": "ext42",
    "internals": {
        "type": "Ext.app.Controller",
        "reference": {
            "name": "items",
            "type": "array"
        },
        "codeClass": null,
        "userConfig": {
            "designer|userClassName": "AdminUser",
            "mixins": [
                "{",
                "        GlobalUtil: 'com.oocl.mnlbc.GlobalMessage'",
                "",
                "}"
            ]
        },
        "name": "HomePage1",
        "cn": [
            {
                "type": "controllerref",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "ref": "adminUserPanel",
                    "selector": "#AdminUserPanel"
                },
                "name": "adminUserPanel"
            },
            {
                "type": "controllerref",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "ref": "userGrid",
                    "selector": "#userGrid"
                },
                "name": "userGrid"
            },
            {
                "type": "controllerref",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "ref": "btnEnable",
                    "selector": "#btnEnable"
                },
                "name": "btnEnable"
            },
            {
                "type": "controllerref",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "ref": "btnDisable",
                    "selector": "#btnDisable"
                },
                "name": "btnDisable"
            },
            {
                "type": "controlleraction",
                "reference": {
                    "name": "listeners",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "designer|controlQuery": "#btnEnable",
                    "designer|targetType": "MyButton30",
                    "fn": "onBtnEnableClick",
                    "implHandler": [
                        " var userStore = Ext.getStore('UsersStore');",
                        "",
                        "                         var usersGrid = this.getUserGrid(),",
                        "                    selectModel = usersGrid.getSelectionModel(),",
                        "                    selectedUser = selectModel.getSelection();",
                        "                    User = selectedUser[0].data;",
                        "",
                        "",
                        "var user ={",
                        "    'address':User.Address,",
                        "    'contactno':User.Contact,",
                        "    'email':User.Email,",
                        "    'firstname':User.Firstname,",
                        "    'gender':User.Gender,",
                        "    'id':User.id,",
                        "    'isDisabled':0,",
                        "    'lastname':User.Lastname,",
                        "    'middlename':User.Middlename,",
                        "    'points':User.Points,",
                        "    'type':User.Type,",
                        "    'userLevel':User.Level,",
                        "    'username':User.Username",
                        "};",
                        "",
                        "       Ext.Ajax.request({",
                        "                    url:'user/updateUser',",
                        "                    headers: { 'Content-Type': 'application/json',",
                        "                     'Accept': 'application/json'},",
                        "                     jsonData:user,",
                        "                    scope:this,",
                        "                    success : function(response) {",
                        "                        Ext.MessageBox.alert('Success',User.Username + ' is now Activated');",
                        "",
                        "                        userStore.removeAll();",
                        "",
                        "                         Ext.Ajax.request({",
                        "                            url : 'user/getAllUsers',",
                        "                            params : {",
                        "",
                        "                            },",
                        "                            scope : this,",
                        "                            success : function(response) {",
                        "                                var data = Ext.decode(response.responseText);",
                        "                                Ext.each(data, function(record){",
                        "                                    var users = {",
                        "                                        id:record.id,",
                        "                                        Username:record.username,",
                        "                                        Password:record.password,",
                        "                                        Firstname:record.firstname,",
                        "                                        Middlename:record.middlename,",
                        "                                        Lastname:record.lastname,",
                        "                                        Gender:record.gender,",
                        "                                        Email:record.email,",
                        "                                        Address:record.address,",
                        "                                        Contact:record.contactno,",
                        "                                        Disabled:record.isDisabled,",
                        "                                        Type:record.type,",
                        "                                        Level:record.userLevel,",
                        "                                        Points:record.points",
                        "",
                        "                                    };",
                        "                                    userStore.add(users);",
                        "                                });",
                        "                            }",
                        "                        });",
                        "",
                        "                    }",
                        "                });",
                        "",
                        ""
                    ],
                    "name": "click",
                    "scope": "me"
                },
                "name": "onBtnEnableClick"
            },
            {
                "type": "controlleraction",
                "reference": {
                    "name": "listeners",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "designer|controlQuery": "#btnDisable",
                    "designer|targetType": "MyButton31",
                    "fn": "onBtnDisableClick",
                    "implHandler": [
                        "",
                        "        var userStore = Ext.getStore('UsersStore');",
                        "",
                        "                         var usersGrid = this.getUserGrid(),",
                        "                    selectModel = usersGrid.getSelectionModel(),",
                        "                    selectedUser = selectModel.getSelection();",
                        "                    User = selectedUser[0].data;",
                        "var user ={",
                        "    'address':User.Address,",
                        "    'contactno':User.Contact,",
                        "    'email':User.Email,",
                        "    'firstname':User.Firstname,",
                        "    'gender':User.Gender,",
                        "    'id':User.id,",
                        "    'isDisabled':1,",
                        "    'lastname':User.Lastname,",
                        "    'middlename':User.Middlename,",
                        "    'points':User.Points,",
                        "    'type':User.Type,",
                        "    'userLevel':User.Level,",
                        "    'username':User.Username",
                        "};",
                        "       Ext.Ajax.request({",
                        "                    url:'user/updateUser',",
                        "                    headers: { 'Content-Type': 'application/json',",
                        "                     'Accept': 'application/json'},",
                        "                     jsonData:user,",
                        "                    scope:this,",
                        "                    success : function(response) {",
                        "                        Ext.MessageBox.alert('Success',User.Username + ' is now Blocked');",
                        "                        var userStore = Ext.getStore('UsersStore');",
                        "                        userStore.removeAll();",
                        "                                                ",
                        "            Ext.Ajax.request({",
                        "                        url : 'user/getAllUsers',",
                        "                        params : {",
                        "",
                        "                        },",
                        "                        scope : this,",
                        "                        success : function(response) {",
                        "                            var data = Ext.decode(response.responseText);",
                        "                            Ext.each(data, function(record){",
                        "                                var users = {",
                        "                                    id:record.id,",
                        "                                    Username:record.username,",
                        "                                    Password:record.password,",
                        "                                    Firstname:record.firstname,",
                        "                                    Middlename:record.middlename,",
                        "                                    Lastname:record.lastname,",
                        "                                    Gender:record.gender,",
                        "                                    Email:record.email,",
                        "                                    Address:record.address,",
                        "                                    Contact:record.contactno,",
                        "                                    Disabled:record.isDisabled,",
                        "                                    Type:record.type,",
                        "                                    Level:record.userLevel,",
                        "                                    Points:record.points",
                        "",
                        "                                };",
                        "                                userStore.add(users);",
                        "                            });",
                        "                        }",
                        "                    });",
                        "",
                        "                    }",
                        "                });",
                        ""
                    ],
                    "name": "click",
                    "scope": "me"
                },
                "name": "onBtnDisableClick"
            },
            {
                "type": "controlleraction",
                "reference": {
                    "name": "listeners",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "designer|controlQuery": "#userGrid",
                    "designer|targetType": "MyGridPanel5",
                    "fn": "onUserGridSelectionChange",
                    "implHandler": [
                        "var userStore = Ext.getStore('UsersStore');",
                        "",
                        "        var usersGrid = this.getUserGrid(),",
                        "            selectModel = usersGrid.getSelectionModel(),",
                        "            selectedUser = selectModel.getSelection();",
                        "",
                        "if(!Ext.isEmpty(selectedUser))  {",
                        "    userDisabledValue = selectedUser[0].data.Disabled;",
                        "    if(userDisabledValue === 0){",
                        "            this.getBtnEnable().disable();",
                        "            this.getBtnDisable().enable();",
                        "            Ext.getCmp('btnManage').enable();",
                        "        }else{",
                        "            this.getBtnEnable().enable();",
                        "            this.getBtnDisable().disable();",
                        "            Ext.getCmp('btnManage').enable();",
                        "        }",
                        "}else{",
                        "    Ext.getCmp('btnManage').disable();",
                        "}",
                        ""
                    ],
                    "name": "selectionchange",
                    "scope": "me"
                },
                "name": "onUserGridSelectionChange"
            },
            {
                "type": "controlleraction",
                "reference": {
                    "name": "listeners",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "designer|controlQuery": "#btnUsers",
                    "designer|targetType": "MyButton25",
                    "fn": "onBtnUsersClick",
                    "implHandler": [
                        "",
                        "    this.getAdminUserPanel().show();",
                        "",
                        " var userStore = Ext.getStore('UsersStore');",
                        "",
                        "userStore.removeAll();",
                        "",
                        "Ext.Ajax.request({",
                        "            url : 'user/getAllUsers',",
                        "            params : {",
                        "",
                        "            },",
                        "            scope : this,",
                        "            success : function(response) {",
                        "                var data = Ext.decode(response.responseText);",
                        "                Ext.each(data, function(record){",
                        "                    var users = {",
                        "                        id:record.id,",
                        "                        Username:record.username,",
                        "                        Password:record.password,",
                        "                        Firstname:record.firstname,",
                        "                        Middlename:record.middlename,",
                        "                        Lastname:record.lastname,",
                        "                        Gender:record.gender,",
                        "                        Email:record.email,",
                        "                        Address:record.address,",
                        "                        Contact:record.contactno,",
                        "                        Disabled:record.isDisabled,",
                        "                        Type:record.type,",
                        "                        Level:record.userLevel,",
                        "                        Points:record.points",
                        "",
                        "                    };",
                        "                    userStore.add(users);",
                        "                });",
                        "            }",
                        "        });",
                        "",
                        ""
                    ],
                    "name": "click",
                    "scope": "me"
                },
                "name": "onBtnUsersClick"
            },
            {
                "type": "controlleraction",
                "reference": {
                    "name": "listeners",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "designer|controlQuery": "#btnManage",
                    "designer|targetType": "MyButton36",
                    "fn": "onBtnManageClick",
                    "implHandler": [
                        "    Ext.create('BurgerQueen.view.WinUserEdit').show();",
                        "",
                        "                var usersGrid = this.getUserGrid(),",
                        "                    selectModel = usersGrid.getSelectionModel(),",
                        "                    selectedUser = selectModel.getSelection(),",
                        "                    type = selectedUser[0].data.Type,",
                        "                    point = selectedUser[0].data.Points;",
                        "",
                        "                Ext.getCmp('UserManageType').setValue(type);",
                        "                Ext.getCmp('manageUserPoints').setValue(point);"
                    ],
                    "name": "click",
                    "scope": "me"
                },
                "name": "onBtnManageClick"
            },
            {
                "type": "controlleraction",
                "reference": {
                    "name": "listeners",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "designer|controlQuery": "#manageUserBtnConfirm",
                    "designer|targetType": "MyButton35",
                    "fn": "onManageUserBtnConfirmClick",
                    "implHandler": [
                        "        var form = this.getAdminManageUserForm();",
                        "        var usersGrid = this.getUserGrid(),",
                        "            selectModel = usersGrid.getSelectionModel(),",
                        "            selectedUser = selectModel.getSelection();",
                        "        User = selectedUser[0].data;",
                        "",
                        " if(form.isValid()){",
                        "     var type = Ext.getCmp('UserManageType').getValue(),",
                        "          points = Ext.getCmp('manageUserPoints').getValue();",
                        "",
                        "    var user ={",
                        "                'address':User.Address,",
                        "                'contactno':User.Contact,",
                        "                'email':User.Email,",
                        "                'firstname':User.Firstname,",
                        "                'gender':User.Gender,",
                        "                'id':User.id,",
                        "                'isDisabled':User.isDisabled,",
                        "                'lastname':User.Lastname,",
                        "                'middlename':User.Middlename,",
                        "                'points':points,",
                        "                'type':type,",
                        "                'userLevel':User.Level,",
                        "                'username':User.Username",
                        "            };",
                        "",
                        "                    Ext.Ajax.request({",
                        "                            url:'user/updateUser',",
                        "                            headers: { 'Content-Type': 'application/json',",
                        "                             'Accept': 'application/json'},",
                        "                             jsonData:user,",
                        "                            scope:this,",
                        "                            success : function(response) {",
                        "                                Ext.MessageBox.alert('Success','User: '+User.Username + ' was updated!');",
                        "                                var userStore = Ext.getStore('UsersStore');",
                        "                                userStore.removeAll();",
                        "",
                        "                    Ext.Ajax.request({",
                        "                                url : 'user/getAllUsers',",
                        "                                params : {",
                        "",
                        "                                },",
                        "                                scope : this,",
                        "                                success : function(response) {",
                        "                                    var data = Ext.decode(response.responseText);",
                        "                                    Ext.each(data, function(record){",
                        "                                        var users = {",
                        "                                            id:record.id,",
                        "                                            Username:record.username,",
                        "                                            Password:record.password,",
                        "                                            Firstname:record.firstname,",
                        "                                            Middlename:record.middlename,",
                        "                                            Lastname:record.lastname,",
                        "                                            Gender:record.gender,",
                        "                                            Email:record.email,",
                        "                                            Address:record.address,",
                        "                                            Contact:record.contactno,",
                        "                                            Disabled:record.isDisabled,",
                        "                                            Type:record.type,",
                        "                                            Level:record.userLevel,",
                        "                                            Points:record.points",
                        "",
                        "                                        };",
                        "                                        userStore.add(users);",
                        "                                    });",
                        "                                }",
                        "                            });",
                        "",
                        "                            }",
                        "                        });",
                        "",
                        "    this.getWinUserEdit().destroy();",
                        "",
                        " }else{",
                        "     Ext.MessageBox.alert('Error', 'Invalid input, please check fields');",
                        " }",
                        "",
                        "",
                        ""
                    ],
                    "name": "click",
                    "scope": "me"
                },
                "name": "onManageUserBtnConfirmClick"
            },
            {
                "type": "controllerref",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "ref": "winUserEdit",
                    "selector": "#winUserEdit"
                },
                "name": "winUserEdit"
            },
            {
                "type": "controllerref",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "ref": "adminManageUserForm",
                    "selector": "#adminManageUserForm"
                },
                "name": "adminManageUserForm"
            }
        ]
    },
    "linkedNodes": {},
    "boundStores": {},
    "boundModels": {}
}