/* CREATES THE TABLES */
CREATE TABLE USERTABLE(
USERID INT NOT NULL,
USERFIRSTNAME VARCHAR2(45),
USERLASTNAME VARCHAR2(45),
PRIMARY KEY (USERID)
);

CREATE TABLE ORDERTABLE(
ORDERID INT NOT NULL,
USERID INT NOT NULL,
ORDERDATE DATE,
PRIMARY KEY (ORDERID),
CONSTRAINT FK_USER FOREIGN KEY (USERID) REFERENCES USERTABLE(USERID)
);

CREATE TABLE ORDERITEM(
ITEMID INT NOT NULL,
ORDERID INT NOT NULL,
ITEMQUANTITY INT NOT NULL,
ITEMDESCRIPTION VARCHAR2(45),
PRIMARY KEY (ITEMID),
CONSTRAINT FK_ORDERTABLE FOREIGN KEY (ORDERID) REFERENCES ORDERTABLE(ORDERID)
);
/*INSERTS VALUES IN THE TABLE */

INSERT INTO USERTABLE
VALUES(1,'JOHN PAUL', 'LIMOS');

INSERT INTO ORDERTABLE
VALUES(1,1,'04-JUL-16');

INSERT INTO ORDERITEM
VALUES(1, 1, 2, 'BAG');

/* SELECTS VALUES FROM TABLES */
SELECT * FROM USERTABLE;
SELECT * FROM ORDERTABLE;
SELECT * FROM ORDERITEM;

/*SELECTS ORDER ITEMS AND QUANTITY FOR EACH USER */
SELECT CUSTOMER.USERFIRSTNAME, ORDERITEM.ITEMDESCRIPTION, ORDERITEM.ITEMQUANTITY
FROM USERTABLE CUSTOMER, ORDERTABLE ORDERT, ORDERITEM ORDERITEM
WHERE CUSTOMER.USERID = ORDERT.USERID AND
ORDERT.ORDERID = ORDERITEM.ORDERID;

/*COMMITS ALL CHANGES */
COMMIT;

/*UPDATE USERTABLE*/
UPDATE USERTABLE SET USERFIRSTNAME = 'JOHN' WHERE USERID = 1;
UPDATE ORDERTABLE SET ORDERDATE = '05-JUL-16' WHERE ORDERID = 1;
UPDATE ORDERITEM SET ITEMDESCRIPTION = 'SHOES' WHERE ITEMID = 1;

/*DELETE ROW*/
DELETE FROM USERTABLE WHERE USERID = 1;
DELETE FROM ORDERTABLE WHERE ORDERID = 1;
DELETE FROM ORDERITEM WHERE ITEMID = 1;

/*ALTER TABLES*/
ALTER TABLE USERTABLE
ADD ADDRESS VARCHAR2(45);

ALTER TABLE USERTABLE
DROP COLUMN ADDRESS;

/*RENAME TABLE ORDERITEM*/
RENAME ORDERITEM TO PURCHASED;

/*GRANT ACCESS*/
GRANT SELECT ON USERTABLE TO LIMOSJO;

/*REVOKES ALL CAPABILITIES TO USER LIMOSJO */
REVOKE ALL ON USERTABLE FROM LIMOSJO;

/*DROPS TABLE */
DROP TABLE USERTABLE;
DROP TABLE ORDERTABLE;
DROP TABLE ORDERITEM;

/*REVERTS ALL CHANGES */
ROLLBACK;
