--1
SELECT * FROM emp WHERE sal > 3000;

--2
SELECT * FROM emp WHERE ename LIKE 'S%'; 

--3
SELECT * FROM emp WHERE ename IN ('SMITH','ALLEN','FORD');

--4
SELECT emp.* , dname FROM dept
JOIN emp 
ON dept.deptno = emp.deptno
WHERE dname = 'SALES';


--5
SELECT B.DNAME, AVG(A.SAL) AVERAGE, MAX(A.SAL) BIGGEST,
MIN(A.SAL)SMALLEST, SUM(A.SAL) TOTAL
FROM EMP A
JOIN DEPT B 
ON B.DEPTNO = A.DEPTNO
GROUP BY B.DNAME
ORDER BY B.DNAME;

--6
SELECT B.DNAME DEPARTMENT, COUNT(A.EMPNO) COUNT
FROM EMP A
JOIN DEPT B 
ON B.DEPTNO = A.DEPTNO
WHERE A.SAL > 3000
GROUP BY B.DNAME;

--7
SELECT dept.dname DEPARTMENT,AVG(emp.sal) AVERAGE FROM EMP 
JOIN dept 
ON dept.deptno = emp.deptno
GROUP BY dept.dname;

--8
SELECT A.DEPTNO DEPT_NUMBER, A.SAL SALARY, COUNT(A.EMPNO) COUNT
FROM EMP A JOIN EMP B
ON A.EMPNO = B.EMPNO
WHERE A.SAL = B.SAL
AND A.DEPTNO = B.DEPTNO
GROUP BY A.DEPTNO, A.SAL
HAVING COUNT(A.EMPNO) > 1;

--9
SELECT B.DNAME DEPARTMENT, B.LOC AREA, COUNT(A.EMPNO) COUNT 
FROM DEPT B
JOIN EMP A ON 
B.DEPTNO = A.DEPTNO
GROUP BY B.DNAME, B.LOC
HAVING COUNT(A.EMPNO) > 2;

--10
SELECT ENAME, SAL FROM EMP 
WHERE SAL > (SELECT AVG(SAL) FROM EMP);
