/*
 * File: app/store/Category.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Project.store.Category', {
    extend: 'Ext.data.Store',

    requires: [
        'Project.model.Category'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Project.model.Category',
            storeId: 'categoryBookStore',
            data: '\'Science fiction\',\n\'Satire\',\n\'Drama\',\n\'Action and Adventure\',\n\'Romance\',\n\'Mystery\',\n\'Horror\',\n\'Self help\',\n\'Health\',\n\'Guide\',\n\'Travel\',\n\'Children\',\n\'Religion, Spirituality & New Age\',\n\'Science\',\n\'History\',\n\'Math\',\n\'Anthology\',\n\'Poetry\',\n\'Encyclopedias\',\n\'Dictionaries\',\n\'Comics\',\n\'Art\',\n\'Cookbooks\',\n\'Diaries\',\n\'Journals\',\n\'Prayer books\',\n\'Series\',\n\'Trilogy\',\n\'Biographies\',\n\'Autobiographies\',\n\'Fantasy\''
        }, cfg)]);
    }
});