/*
 * File: resources/app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BurgerQueen.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'BurgerQueen.view.Products',
        'BurgerQueen.view.UserProfile',
        'BurgerQueen.view.AdminProductsPanel',
        'BurgerQueen.view.AdminTransactionsPanel',
        'BurgerQueen.view.AdminUserPanel',
        'BurgerQueen.view.AdminCommentsPanel',
        'BurgerQueen.view.AdminOrderManagementPanel',
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.Img'
    ],

    html: '<link href=\'http://fonts.googleapis.com/css?family=Abel\' rel=\'stylesheet\' type=\'text/css\'>',
    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'BurgerQueen',
                    itemId: 'BurgerQueen',
                    layout: 'fit',
                    header: false,
                    title: 'My Panel',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'loginButton',
                                    style: 'font-family:\'Abel\';\nfont-size:20px;',
                                    ui: 'menubarbtn',
                                    text: 'LOGIN |'
                                },
                                {
                                    xtype: 'button',
                                    id: 'registerButton',
                                    itemId: 'registerButton',
                                    style: 'font-family:\'Abel\';\nfont-size:20px;',
                                    ui: 'menubarbtn',
                                    text: 'REGISTER |'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'myProfileButton',
                                    itemId: 'myProfileButton',
                                    style: 'font-family:\'Abel\';\nfont-size:20px;',
                                    ui: 'menubarbtn',
                                    text: 'MY PROFILE'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'trayButton',
                                    itemId: 'trayButton',
                                    style: 'font-family:\'Abel\';;\nfont-size:20px;',
                                    ui: 'menubarbtn',
                                    text: 'MY TRAY |'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    itemId: 'logoutButton',
                                    style: 'font-family:\'Abel\';\nfont-size:20px;',
                                    ui: 'menubarbtn',
                                    text: 'LOGOUT |'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'showUsersWindow',
                                    style: 'font-family:\'Abel\';\nfont-size:20px;',
                                    ui: 'menubarbtn',
                                    text: 'ACTIVE USERS'
                                },
                                {
                                    xtype: 'displayfield',
                                    itemId: 'activeUsersCount',
                                    style: 'font-family:\'Abel\';\nfont-size:22px;',
                                    fieldLabel: '',
                                    labelWidth: 50,
                                    value: '0'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            id: 'toolBarCustomer',
                            style: 'background-color:#ff9e14;\nfont-color:white;',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'image',
                                    height: 60,
                                    width: 60,
                                    src: 'resources/images/Logo.png'
                                },
                                {
                                    xtype: 'button',
                                    id: 'allCategoriesButton',
                                    itemId: 'allCategoriesButton',
                                    style: 'font-family: \'Insaniburger with Cheese\';\n    font-size:35px;\n    color:white;',
                                    ui: 'menubarbtn',
                                    text: 'All Categories |'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'beveragesButton',
                                    style: 'font-family: \'Insaniburger with Cheese\';\n    font-size:35px; \n    color:white;',
                                    ui: 'menubarbtn',
                                    text: 'Beverages |'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'burgersButton',
                                    style: 'font-family: \'Insaniburger with Cheese\';\n    font-size:35px;\n  color:white;',
                                    ui: 'menubarbtn',
                                    text: 'Burgers |'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'chickensButton',
                                    style: 'font-family: \'Insaniburger with Cheese\';\n    font-size:35px;\n     color:white;',
                                    ui: 'menubarbtn',
                                    text: 'Chickens |'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'dessertsButton',
                                    style: 'font-family: \'Insaniburger with Cheese\';\n    font-size:35px;\n     color:white;',
                                    ui: 'menubarbtn',
                                    text: 'Desserts |'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'sidesButton',
                                    style: 'font-family: \'Insaniburger with Cheese\';\n    font-size:35px;\n     color:white;',
                                    ui: 'menubarbtn',
                                    text: 'Sides'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnContactUs',
                                    itemId: 'btnContactUs',
                                    style: 'font-family: \'Insaniburger with Cheese\';\n    font-size:35px;\n     color:white;',
                                    ui: 'menubarbtn',
                                    text: '| Contact Us'
                                }
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            hidden: true,
                            id: 'toolBarAdmin',
                            itemId: 'toolBarAdmin',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnUsers',
                                    itemId: 'btnUsers',
                                    text: 'Users'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'btnProducts',
                                    itemId: 'btnProducts',
                                    text: 'Products'
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'btnTransactions',
                                    itemId: 'btnTransactions',
                                    text: 'Transactions'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnOrderManagement',
                                    itemId: 'btnOrderManagement',
                                    text: 'Order Management'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnComments',
                                    itemId: 'btnComments',
                                    text: 'Comments'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'Products'
                        },
                        {
                            xtype: 'userprofile',
                            hidden: true
                        },
                        {
                            xtype: 'adminproductspanel'
                        },
                        {
                            xtype: 'admintransactionspanel'
                        },
                        {
                            xtype: 'adminuserpanel'
                        },
                        {
                            xtype: 'admincommentspanel1'
                        },
                        {
                            xtype: 'adminordermanagementpanel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});