/*
 * File: app/view/Homepage.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BookingManagementSystem.view.Homepage', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Number'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    frameHeader: false,
                    header: false,
                    overlapHeader: false,
                    title: 'Booking Ma System',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    text: 'Welcome '
                                },
                                {
                                    xtype: 'button',
                                    text: 'Logout'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    title: 'Books',
                                    tabConfig: {
                                        xtype: 'tab',
                                        flex: 1
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Enter Title'
                                                },
                                                {
                                                    xtype: 'button',
                                                    text: 'Search'
                                                }
                                            ]
                                        }
                                    ],
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            title: 'All books',
                                            store: 'bookStore',
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    dataIndex: 'string',
                                                    text: 'Title',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    text: 'Author',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    text: 'Description',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    text: 'Available for rental',
                                                    flex: 1
                                                },
                                                {
                                                    xtype: 'gridcolumn',
                                                    text: 'CheckoutBy',
                                                    flex: 1
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    title: 'User Profile',
                                    tabConfig: {
                                        xtype: 'tab',
                                        flex: 1
                                    }
                                },
                                {
                                    xtype: 'panel',
                                    title: 'Users',
                                    tabConfig: {
                                        xtype: 'tab',
                                        flex: 1
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});