/*
 * File: app/view/viewBookWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BookingManagementSystem.view.viewBookWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.TextArea',
        'Ext.form.field.Number',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    height: 680,
    id: 'viewBookWindow',
    width: 810,
    layout: 'vbox',
    title: 'View/Edit Book',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 276,
                    id: 'viewBookPanel',
                    width: 810,
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            id: 'viewBookInformationContainer',
                            width: 600,
                            title: 'Book Information',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'titleView',
                                    fieldLabel: 'Title',
                                    name: 'title',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: 'authorView',
                                    fieldLabel: 'Author',
                                    name: 'author',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    id: 'descriptionView',
                                    fieldLabel: 'Description',
                                    name: 'description',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    id: 'availableView',
                                    fieldLabel: 'Available for rental',
                                    name: 'available',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false,
                                    allowDecimals: false,
                                    allowExponential: false,
                                    decimalPrecision: 0,
                                    minValue: 1
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            id: 'viewSaveBookButton',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            id: 'viewCancelSaveBookButton',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});