/*
 * File: app/view/registerWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BookingManagementSystem.view.registerWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    draggable: false,
    height: 500,
    id: 'registerWindow',
    width: 400,
    title: 'Register',

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    flex: 1,
                    id: 'registerPanel',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 370,
                            id: 'RegisterWindow',
                            padding: 40,
                            width: 345,
                            title: 'Enter Credentials',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    id: '',
                                    itemId: 'firstName',
                                    fieldLabel: 'First Name',
                                    name: 'firstName',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'lastName',
                                    fieldLabel: 'Last Name',
                                    name: 'lastName',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'userName',
                                    fieldLabel: 'UserName',
                                    name: 'userName',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'password',
                                    fieldLabel: 'Password',
                                    name: 'password',
                                    inputType: 'password',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'contactNo',
                                    fieldLabel: 'Contact No.',
                                    name: 'contactNo',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    itemId: 'email',
                                    fieldLabel: 'Email',
                                    name: 'email',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                },
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    itemId: 'address',
                                    fieldLabel: 'Address',
                                    name: 'address',
                                    allowBlank: false,
                                    allowOnlyWhitespace: false
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            margin: 10,
                            shadow: true,
                            layout: {
                                type: 'hbox',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'submitButton',
                                    text: 'Submit'
                                },
                                {
                                    xtype: 'button',
                                    id: 'cancelButton',
                                    text: 'Cancel'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});