/*
 * File: app/view/SignUpWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Project.view.SignUpWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    height: 329,
    itemId: 'signUpWindow',
    width: 398,
    bodyPadding: 15,
    closable: false,
    title: 'Sign Up',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'signUpForm',
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'usernameSignUp',
                            fieldLabel: 'Username',
                            inputId: 'username',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'passwordSignUp',
                            fieldLabel: 'Password',
                            inputId: 'password',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'passwordReSignUp',
                            fieldLabel: 'Re- Password',
                            inputId: 'password2',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            itemId: 'addressSignUp',
                            fieldLabel: 'Address',
                            inputId: 'address',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'phoneSignUp',
                            fieldLabel: 'Phone',
                            inputId: 'phone',
                            allowBlank: false,
                            allowOnlyWhitespace: false
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cancelBttn',
                                    text: 'Cancel'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'registerBttn',
                                    text: 'Register',
                                    listeners: {
                                        click: {
                                            fn: me.onRegisterBttnClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRegisterBttnClick: function(button, e, eOpts) {

    }

});