/*
 * File: app/controller/AdminMenuController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BurgerQueenAdmin.controller.AdminMenuController', {
    extend: 'Ext.app.Controller',

    oLoadingMessageMask: null,

    refs: [
        {
            ref: 'adminCommentsPanel',
            selector: '#adminCommentsPanel'
        },
        {
            ref: 'adminMenu',
            selector: '#adminMenu'
        },
        {
            ref: 'adminCreateMessagePanel',
            selector: '#adminCreateMessagePanel'
        },
        {
            ref: 'adminInquiriesPanel',
            selector: '#adminInquiriesPanel'
        },
        {
            ref: 'adminUserPanel',
            selector: '#adminUserPanel'
        },
        {
            ref: 'adminProductsPanel',
            selector: '#adminProductsPanel'
        },
        {
            ref: 'adminOrderManagementPanel',
            selector: '#AdminOrderManagementPanel'
        },
        {
            ref: 'showUsersWindow',
            selector: '#showUsersWindow'
        },
        {
            ref: 'activeUsersWindow',
            selector: '#ActiveUsersWindow'
        },
        {
            ref: 'activeUsersCount',
            selector: '#activeUsersCount'
        }
    ],

    onAdminUsersButtonClick: function() {
            this.getAdminMenu().hide();
            this.getAdminUserPanel().show();
            this.getAdminProductsPanel().hide();
            this.getAdminOrderManagementPanel().hide();
            this.getAdminInquiriesPanel().hide();
            this.getAdminCreateMessagePanel().hide();
            this.getAdminCommentsPanel().hide();
            this.activeUserCounter();

        this.showLoadingMessageMask();
         var userStore = Ext.getStore('UsersStore');
        userStore.removeAll();
        Ext.Ajax.request({
                    url : 'user/getAllUsers',
                    params : {

                    },
                    scope : this,
                    success : function(response) {
                        var data = Ext.decode(response.responseText);
                        Ext.each(data, function(record){
                            var users = {
                                id:record.id,
                                Username:record.username,
                                Password:record.password,
                                Firstname:record.firstname,
                                Middlename:record.middlename,
                                Lastname:record.lastname,
                                Gender:record.gender,
                                Email:record.email,
                                Address:record.address,
                                Contact:record.contactno,
                                Disabled:record.isDisabled,
                                Type:record.type,
                                Level:record.userLevel,
                                Points:record.points

                            };
                            userStore.add(users);
                        });
                        this.hideLoadingMessageMask();
                    }
                });


    },

    onAdminProductsButtonClick: function() {
            this.getAdminMenu().hide();
            this.getAdminUserPanel().hide();
            this.getAdminProductsPanel().show();
            this.getAdminOrderManagementPanel().hide();
            this.getAdminInquiriesPanel().hide();
            this.getAdminCreateMessagePanel().hide();
            this.getAdminCommentsPanel().hide();
            this.activeUserCounter();
        this.showLoadingMessageMask();
        var store = Ext.getStore('ProductStore');
        store.removeAll();
        Ext.Ajax.request({
            url : 'meal/getAllMeals',
            params : {

            },
            scope : this,
            success : function(response) {
                var data = Ext.JSON.decode(response.responseText);
                Ext.each(data, function(record){
                    var product = {
                        Id:record.id,
                        Code:record.code,
                        Name:record.name,
                        Description:record.description,
                        Category:record.category,
                        Price:record.price,
                        Image:record.image,
                        Points:record.points
                    };
                    store.add(product);
                });
                this.hideLoadingMessageMask();
            }
        });

    },

    onAdminOrdersButtonClick: function() {
            this.getAdminMenu().hide();
            this.getAdminUserPanel().hide();
            this.getAdminProductsPanel().hide();
            this.getAdminOrderManagementPanel().show();
            this.getAdminInquiriesPanel().hide();
            this.getAdminCreateMessagePanel().hide();
            this.getAdminCommentsPanel().hide();
            this.activeUserCounter();
        this.showLoadingMessageMask();

            var store = Ext.getStore('AdminOrderManagementStore');

                    Ext.Ajax.request({
                        url : 'order/getAllOrders',
                        params : {

                        },
                        scope : this,
                        success : function(response) {
                            var data = Ext.JSON.decode(response.responseText);
                            Ext.each(data, function(record){
                                var order = {
                                    id:record.id,
                                    userId:record.user.id,
                                    status:record.status
                                };
                                store.add(order);

                            });
                            this.hideLoadingMessageMask();
                        }
                    });

    },

    onAdminProductFeedbackButtonClick: function() {
            this.getAdminMenu().hide();
            this.getAdminUserPanel().hide();
            this.getAdminProductsPanel().hide();
            this.getAdminOrderManagementPanel().hide();
            this.getAdminInquiriesPanel().hide();
            this.getAdminCreateMessagePanel().hide();
            this.getAdminCommentsPanel().show();
            this.activeUserCounter();
        this.showLoadingMessageMask();
            var store = Ext.getStore('AdminCommentsStore');
            store.removeAll();
                             Ext.Ajax.request({
                                     url : 'feedback/getAllFeedbacks',
                                     params : {
                                     },
                                     scope : this,
                                     success : function(response) {
                                         var data = response.responseText;
                                         var decodedData = Ext.decode(data);
                                         Ext.each(decodedData, function(record){
                                             var adminComment = {
                                                     Id: record.id,
                                                     User: record.user.id,
                                                     Meal: record.meal.id,
                                                     Feedback: record.feedback
                                                 };
                                             store.add(adminComment);
                                         });
                                         this.hideLoadingMessageMask();
                                     }
                                });

    },

    onAdminInquiriesButtonClick: function() {
            this.getAdminMenu().hide();
            this.getAdminUserPanel().hide();
            this.getAdminProductsPanel().hide();
            this.getAdminOrderManagementPanel().hide();
            this.getAdminInquiriesPanel().show();
            this.getAdminCreateMessagePanel().hide();
            this.getAdminCommentsPanel().hide();
            this.activeUserCounter();
        this.showLoadingMessageMask();
            var store = Ext.getStore('AdminInquiryStore');
            store.removeAll();
                             Ext.Ajax.request({
                                     url : 'inquiry/getAllInquiries',
                                     params : {
                                     },
                                     scope : this,
                                     success : function(response) {
                                         var data = response.responseText;
                                         var decodedData = Ext.decode(data);
                                         Ext.each(decodedData, function(record){
                                             var adminInquiry = {
                                                     Id: record.id,
                                                     User: record.user.username,
                                                     Message: record.message,
                                                     DateCreated: record.date_created
                                                 };
                                             store.add(adminInquiry);
                                         });
                                         this.hideLoadingMessageMask();
                                     }
                                });

    },

    onAdminCreateMessageButtonClick: function() {
        this.getAdminMenu().hide();
        this.getAdminUserPanel().hide();
        this.getAdminProductsPanel().hide();
        this.getAdminOrderManagementPanel().hide();
        this.getAdminInquiriesPanel().hide();
        this.getAdminCreateMessagePanel().show();
        this.getAdminCommentsPanel().hide();
            this.activeUserCounter();
        var store = Ext.getStore('AdminMessageStore');
        store.removeAll();

                                        Ext.Ajax.request({
                                                      url:'message/viewMessage',
                                                      params:{
                                                      },
                                                       scope:this,
                                                       success : function(response) {
                                                         var data = response.responseText;

                                                         if(!Ext.isEmpty(data)){
                                                             var decodedData = Ext.decode(data);
                                                             Ext.each(decodedData, function(record){
                                                                var message = {
                                                                    Message : record

                                                                };
                                                                 store.add(message);
                                                             });
                                                         }else{
                                                         }

                                                      }
                                                  });
    },

    onShowUsersWindowClick: function() {
        Ext.create('BurgerQueenAdmin.view.ActiveUsersWindow').show();
        this.activeUserCounter();
    },

    showLoadingMessageMask: function() {
                            if (!this.oLoadingMessageMask) {
                               this.oLoadingMessageMask = new Ext.LoadMask(Ext.getBody(), {
                                  msg : "Loading, please wait..."
                               });
                            }
                            this.oLoadingMessageMask.show();
    },

    hideLoadingMessageMask: function() {

                            if (this.oLoadingMessageMask) {
                               this.oLoadingMessageMask.hide();
                            }
    },

    activeUserCounter: function() {


            Ext.Ajax.request({
                    url : 'getLoggedUsers',
                    params : {

                    },
                    scope : this,
                    success : function(response) {
                        var data = Ext.decode(response.responseText);
                        activeUsers = data;
                        activeUser = true;
                        var store = Ext.getStore('ActiveUserStore');
                        store.removeAll();
                       this.getActiveUsersCount().setValue(data.length);
                        Ext.each(data, function(record){
                            store.add({username:record.username});
                        });

                    }
                });
    },

    init: function(application) {
        this.control({
            "#adminUsersButton": {
                click: this.onAdminUsersButtonClick
            },
            "#adminProductsButton": {
                click: this.onAdminProductsButtonClick
            },
            "#adminOrdersButton": {
                click: this.onAdminOrdersButtonClick
            },
            "#adminProductFeedbackButton": {
                click: this.onAdminProductFeedbackButtonClick
            },
            "#adminInquiriesButton": {
                click: this.onAdminInquiriesButtonClick
            },
            "#adminCreateMessageButton": {
                click: this.onAdminCreateMessageButtonClick
            },
            "#showUsersWindow": {
                click: this.onShowUsersWindowClick
            }
        });
    }

});
