/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('W3D3.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 325,
                    width: 670,
                    layout: 'vbox',
                    bodyPadding: 10,
                    title: 'W3D3 Homework',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 620,
                            fieldLabel: 'Name'
                        },
                        {
                            xtype: 'textfield',
                            width: 620,
                            fieldLabel: 'Email'
                        },
                        {
                            xtype: 'textfield',
                            width: 620,
                            fieldLabel: 'Phone'
                        },
                        {
                            xtype: 'textareafield',
                            width: 620,
                            fieldLabel: 'Address'
                        },
                        {
                            xtype: 'datefield',
                            width: 620,
                            fieldLabel: 'Birthday'
                        },
                        {
                            xtype: 'radiogroup',
                            width: 670,
                            fieldLabel: 'Gender',
                            items: [
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Male'
                                },
                                {
                                    xtype: 'radiofield',
                                    boxLabel: 'Female'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Register'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});