/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Project.controller.LoginController', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'login',
            selector: '#login'
        },
        {
            ref: 'usernameTextField',
            selector: '#usernameTextField'
        },
        {
            ref: 'passwordTextField',
            selector: '#passwordTextField'
        }
    ],

    onLoginClick: function() {
                 var username = this.getUsernameTextField().getValue();
                 var password = this.getPasswordTextField().getValue();

                 this.userStore = Ext.create('Project.store.User');

                //logic checking if the user exist in the store
                console.log('Username' + username);
                console.log('Password' + password);

                Ext.each(this.userStore.getRange(), function(record){
                     var data = record.data;
                    if(data.username === username && data.password === password){
                        console.log('success');
                        return false;
                    }
                });



    },

    onCancelLoginClick: function(button) {
            var window = button.up('window');
                window.hide();
                this.getUsernameTextField().setValue('');
                this.getPasswordTextField().setValue('');
    },

    init: function(application) {
        this.control({
            "#login": {
                click: this.onLoginClick
            },
            "#cancelLogin": {
                click: this.onCancelLoginClick
            }
        });
    }

});
