/*
CREATE TABLE USERS
*/

DROP TABLE USERS;
DROP SEQUENCE USER_ID_SEQ;
DROP TRIGGER USER_ID_TRIG;

CREATE TABLE USERS(
	 ID             NUMBER(15)   NOT NULL PRIMARY KEY
	,USERNAME       VARCHAR(40)  UNIQUE NOT NULL 
	,PASSWORD       VARCHAR(100) NOT NULL
	,FIRSTNAME      VARCHAR(60)  NOT NULL
	,MIDDLENAME     VARCHAR(60)  NOT NULL
	,LASTNAME       VARCHAR(60)  NOT NULL
	,GENDER 		VARCHAR(60)  NOT NULL
	,EMAIL          VARCHAR(100) NOT NULL
	,ADDRESS        VARCHAR(200) NOT NULL
	,CONTACTS       VARCHAR(15) 
	,IS_DISABLED    NUMBER(1)    NOT NULL
	,TYPE           VARCHAR(10)  NOT NULL
);

CREATE SEQUENCE USER_ID_SEQ START WITH 100001 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USER_ID_TRIG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN
SELECT USER_ID_SEQ.nextval INTO :new.ID FROM DUAL;
END IF;
END;

INSERT INTO USERS (
USERNAME
,PASSWORD
,FIRSTNAME
,MIDDLENAME
,LASTNAME
,GENDER
,EMAIL
,ADDRESS
,CONTACTS
,IS_DISABLED
,TYPE 
)
VALUES ('admin','admin','Peter','Visda','Barredo','Male','pvbarredo@gmail.com','greenheights village','092182',0,'admin');

SELECT * FROM users;


/*
CREATE MEAL
*/
DROP TABLE MEAL;
DROP SEQUENCE MEAL_ID_SEQ;
DROP TRIGGER MEAL_ID_TRIG;

CREATE TABLE MEAL(
	 ID             NUMBER(15)   NOT NULL PRIMARY KEY
	,CODE       	VARCHAR(40)  UNIQUE NOT NULL 
	,NAME       	VARCHAR(100) NOT NULL
	,PRICE			FLOAT(126)	 NOT NULL
	,DESCRIPTION    VARCHAR(200) NOT NULL
	,IMAGE			VARCHAR(200) 
);

CREATE SEQUENCE MEAL_ID_SEQ START WITH 100001 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER MEAL_ID_TRIG
BEFORE INSERT ON MEAL
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN
SELECT MEAL_ID_SEQ.nextval INTO :new.ID FROM DUAL;
END IF;
END;

INSERT INTO MEAL (
 CODE       
,NAME
,PRICE       
,DESCRIPTION
,IMAGE	
)
VALUES ('M1',20,'Rice','Sinandomeng','C:\IMAGE');

/*
CREATE COMBO MEAL
*/
DROP TABLE COMBO_MEAL;
DROP SEQUENCE COMBO_MEAL_ID_SEQ;
DROP TRIGGER COMBO_MEAL_ID_TRIG;

CREATE TABLE COMBO_MEAL(
	 ID             NUMBER(15)   NOT NULL PRIMARY KEY
	,CODE       	VARCHAR(40)  UNIQUE NOT NULL 
	,NAME       	VARCHAR(100) NOT NULL
	,PRICE			FLOAT(126)	 NOT NULL
	,DESCRIPTION    VARCHAR(200) NOT NULL
	,IMAGE			VARCHAR(200) 
);

CREATE SEQUENCE COMBO_MEAL_ID_SEQ START WITH 100001 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER COMBO_MEAL_ID_TRIG
BEFORE INSERT ON COMBO_MEAL
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN
SELECT COMBO_MEAL_ID_SEQ.nextval INTO :new.ID FROM DUAL;
END IF;
END;

INSERT INTO COMBO_MEAL (
 CODE
,PRICE  
,NAME       
,DESCRIPTION
,IMAGE	
)
VALUES ('M1',20,'39ers','CHICKEN RICE','C:\IMAGE');



/*
Create Orders
*/

DROP TABLE ORDERS;
DROP SEQUENCE ORDERS_ID_SEQ;
DROP TRIGGER ORDERS_ID_TRIG;

CREATE TABLE ORDERS(
	 ID             NUMBER(15)   NOT NULL PRIMARY KEY
	,USERS_ID      	NUMBER(15) 	 NOT NULL 
	,STATUS       	VARCHAR(40)  NOT NULL
);

CREATE SEQUENCE ORDERS_ID_SEQ START WITH 100001 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ORDERS_ID_TRIG
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
IF :new.ID IS NULL THEN
SELECT ORDERS_ID_SEQ.nextval INTO :new.ID FROM DUAL;
END IF;
END;

ALTER TABLE ORDERS ADD CONSTRAINT FK_USER_ID FOREIGN KEY (ID) REFERENCES USERS (ID);

INSERT INTO ORDERS (
 USERS_ID
,STATUS  
)
VALUES (1,'Waiting');



