/*
 * File: app/store/BorrowedStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Libray.store.BorrowedStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Libray.model.BorrowedModel',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Libray.model.BorrowedModel',
            storeId: 'BorrowedStore',
            fields: [
                {
                    name: 'title'
                },
                {
                    name: 'author'
                },
                {
                    name: 'publisher'
                }
            ]
        }, cfg)]);
    }
});